In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("../DATASETS/Global_world.csv")
df

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [3]:
df.columns = df.columns.str.replace(" ","")

In [6]:
df.columns = df.columns.str.replace("-","")

In [9]:
df.columns = df.columns.str.replace("/","")

In [11]:
df.columns = df.columns.str.replace("[(%)]","",regex=True)

In [13]:
df=df.rename(columns={'Density\nPKm2':'Density','LandAreaKm2':'LandArea','Population:Laborforceparticipation':'PopulationLaborforceparticipation'})

In [15]:
df.columns

Index(['Country', 'Density', 'Abbreviation', 'AgriculturalLand', 'LandArea',
       'ArmedForcessize', 'BirthRate', 'CallingCode', 'CapitalMajorCity',
       'Co2Emissions', 'CPI', 'CPIChange', 'CurrencyCode', 'FertilityRate',
       'ForestedArea', 'GasolinePrice', 'GDP',
       'Grossprimaryeducationenrollment', 'Grosstertiaryeducationenrollment',
       'Infantmortality', 'Largestcity', 'Lifeexpectancy',
       'Maternalmortalityratio', 'Minimumwage', 'Officiallanguage',
       'Outofpockethealthexpenditure', 'Physiciansperthousand', 'Population',
       'PopulationLaborforceparticipation', 'Taxrevenue', 'Totaltaxrate',
       'Unemploymentrate', 'Urban_population', 'Latitude', 'Longitude'],
      dtype='object')

In [17]:
df.Density=df.Density.replace(',','',regex=True).astype('int64')

In [19]:
df.Density.unique()

array([   60,   105,    18,   164,    26,   223,    17,   104,     3,
         109,   123,    39,  2239,  1265,   668,    47,   383,   108,
          20,    11,    64,     4,    25,    83,    76,   463,   138,
          95,    56,     8,    13,   153,    46,   467,    16,   100,
          73,   106,   131,   139,    40,   137,    43,    96,   225,
          71,   103,   313,    50,    35,    31,    67,   115,    49,
         119,     9,   239,    57,   240,    81,   331,   167,    53,
          70,   414,  2003,    89,   107,   464,   151,    52,    93,
          72,   400,   206,   273,   347,     7,    94,   147,    34,
          32,    30,   667,   238,   242,    48,   203,    99,  1802,
        1380,   329,     5,   626,    66,   784, 26337,     2,   541,
         508,    55,    19,   226,   214,    15,   287,   847,    58,
         368,   124,   111,   248,    84,   525,   205,   301,   284,
         566,   228,    87,  8358,   114,   527,   341,   219,    68,
         152,   110,   393,   229,    75,   118,   281,    36,    79,
         314,    38], dtype=int64)

In [21]:
df.AgriculturalLand=df.AgriculturalLand.replace('%','',regex=True)

In [23]:
df.AgriculturalLand=df.AgriculturalLand.fillna(0).astype('float64')

In [25]:
df.AgriculturalLand.unique()

array([58.1, 43.1, 17.4, 40. , 47.5, 20.5, 54.3, 58.9, 48.2, 32.4, 57.7,
        1.4, 11.1, 70.6, 23.3, 42. , 44.6,  7. , 33.3, 13.6, 34.8, 45.6,
       33.9,  2.7, 46.3, 44.2, 79.2, 64.8, 19.6, 30.9, 20.6,  6.9,  8.2,
       39.7, 21.2, 56.2, 40.3, 71.5, 31.1, 34.5, 27.6, 59.9, 12.2, 45.2,
       11.6, 62. , 73.4, 48.7, 22.2,  3.8, 76.4, 10.1, 75.2, 23.1,  0. ,
       36.3,  7.5, 52.4, 20. , 59.8, 47.7, 69. , 47.6, 23.5, 36. , 59. ,
       58. ,  8.6, 66.8, 28.9, 58.4, 18.7, 60.4, 31.5, 28.2, 21.4, 64.5,
       24.6, 43.2, 41. , 12.3, 12. , 80.4, 48.5,  8.4, 55. , 10.3, 64.3,
       77.6, 28. ,  8.7, 32.2, 47.2, 53.7, 71.2, 61.4, 26.3, 33.8, 63.9,
       38.5, 42.4, 54.6, 31.4, 74.2, 19. , 68.5, 63.5, 19.5, 47.1, 28.7,
       53.3, 40.5, 42.1, 36.1, 77.7, 21.8,  4.6, 47.8, 10.9, 30.4,  2.6,
       55.1, 18.5, 41.7, 46.9, 39.5,  5.8, 58.8, 13.3, 25.6, 12.4, 16.7,
       50.7, 80.8, 46.1, 39.3,  3.4, 54.7,  0.9, 39.2, 30.7,  3.9, 70.3,
       79.8, 52.6, 43.7,  0.6,  7.4, 38.4, 75.8, 34.1, 44.8, 43.3, 70.2,
       45.8, 10.5, 49.8, 72. , 60. , 71.9, 71.7,  5.5, 44.4, 82.6, 62.9,
       15.3, 24.5, 32.1, 41.9])

In [27]:
df.LandArea=df.LandArea.replace(',','',regex=True)

In [29]:
#df.LandArea=df.LandArea.str.replace('0','',regex=True)

In [31]:
df.LandArea=df.LandArea.fillna(0).astype('int64')

In [33]:
df.LandArea.fillna(0).unique()

array([  652230,    28748,  2381741,      468,  1246700,      443,
        2780400,    29743,  7741220,    83871,    86600,    13880,
            765,   148460,      430,   207600,    30528,    22966,
         112622,    38394,  1098581,    51197,   581730,  8515770,
           5765,   110879,   274200,    27830,   322463,     4033,
         181035,   475440,  9984670,   622984,  1284000,   756096,
        9596960,  1138910,     2235,   342000,    51100,    56594,
         110860,     9251,    78867,  2344858,    43094,    23200,
            751,    48670,   283561,  1001450,    21041,    28051,
         117600,    45228,    17364,  1104300,    18274,   338145,
         643801,   267667,    11300,    69700,   357022,   238533,
         131957,      349,   108889,   245857,    36125,   214969,
          27750,        0,   112090,    93028,   103000,  3287263,
        1904569,  1648195,   438317,    70273,    20770,   301340,
          10991,   377944,    89342,  2724900,   580367,      811,
          17818,   199951,   236800,    64589,    10400,    30355,
         111369,  1759540,      160,    65300,     2586,   587041,
         118484,   329847,      298,  1240192,      316,      181,
        1030700,     2040,  1964375,      702,    33851,        2,
        1564116,    13812,   446550,   799380,   676578,   824292,
             21,   147181,    41543,   268838,   130370,  1267000,
         923768,   120538,    25713,   323802,   309500,   796095,
            459,    75420,   462840,   406752,  1285216,   300000,
         312685,    92212,    11586,   238391, 17098240,    26338,
            261,      616,      389,     2831,       61,      964,
        2149690,   196722,    77474,      455,    71740,      716,
          49035,    20273,    28896,   637657,  1219090,    99720,
         644329,   505370,    65610,  1861484,   163820,   450295,
          41277,   185180,   144100,   947300,   513120,    14874,
          56785,      747,     5128,   163610,   783562,   488100,
             26,   241038,   603550,    83600,   243610,  9833517,
         176215,   447400,    12189,   912050,   331210,   527968,
         752618,   390757], dtype=int64)

In [35]:
df.ArmedForcessize=df.ArmedForcessize.replace(',','',regex=True)

In [37]:
df.ArmedForcessize=df.ArmedForcessize.fillna(0).astype('int64')

In [39]:
df.ArmedForcessize.unique()

array([ 323000,    9000,  317000,       0,  117000,  105000,   49000,
         58000,   21000,   82000,    1000,   19000,  221000,  155000,
         32000,    2000,   12000,    6000,   71000,   11000,  730000,
          8000,   31000,   27000,  191000,   24000,   72000,   35000,
        122000, 2695000,  481000,   10000,   18000,   76000,   16000,
         23000,  134000,   15000,   13000,   41000,  836000,   42000,
        202000,  138000,    4000,   25000,  307000,    7000,   26000,
        180000,  146000,   43000,    3000,   40000, 3031000,  676000,
        563000,  209000,  178000,  347000,  261000,  116000,   29000,
        129000,   80000,   34000,   22000,  136000,    5000,  336000,
        246000,  513000,  112000,  215000, 1469000,   47000,  936000,
        158000,  153000,   52000,  126000, 1454000,  252000,   81000,
         20000,  634000,  185000,  196000,  124000,   30000,  239000,
         17000,   28000,  455000,   48000,  512000,   46000,  297000,
         63000,  148000, 1359000,   68000,  343000,  522000,   51000],
      dtype=int64)

In [41]:
df.BirthRate.fillna(0).unique().astype('float64')

array([32.49, 11.78, 24.28,  7.2 , 40.73, 15.33, 17.02, 13.99, 12.6 ,
        9.7 , 14.  , 13.97, 18.18, 10.65,  9.9 , 10.3 , 20.79, 36.22,
       17.26, 21.75,  8.11, 24.82, 13.92, 14.9 ,  8.9 , 37.93, 39.01,
       35.74, 19.49, 22.46, 35.39, 10.1 , 35.35, 42.17, 12.43, 10.9 ,
       14.88, 31.88, 32.86,  9.  , 10.17, 10.46, 10.7 , 41.18, 10.6 ,
       21.47, 12.  , 19.51, 19.72, 26.38, 18.25, 33.24, 30.3 ,  0.  ,
       32.34, 21.28,  8.6 , 11.3 , 31.61, 38.54, 13.47,  9.5 , 29.41,
        8.1 , 16.47, 24.56, 36.36, 35.13, 19.97, 24.35, 21.6 ,  9.6 ,
       17.86, 18.07, 18.78, 29.08, 12.5 , 20.8 ,  7.3 , 16.1 ,  7.4 ,
       21.98, 21.77, 28.75, 27.89, 13.94, 27.1 , 23.55, 10.  , 17.55,
       26.81, 33.04, 18.83, 32.66, 34.12, 16.75, 14.2 , 41.54,  9.2 ,
       29.03, 33.69, 10.2 , 17.6 , 22.82,  5.9 , 24.13, 11.73, 18.94,
       37.52, 28.64, 19.89, 11.98, 20.64, 46.08, 37.91, 13.89, 10.4 ,
       19.19, 28.25, 18.98, 27.07, 20.57, 17.95, 20.55,  8.5 ,  9.54,
       11.5 , 31.7 , 14.24, 24.38,  6.8 , 31.54, 17.8 , 34.52, 17.1 ,
       33.41,  8.8 ,  9.4 , 32.44, 41.75, 20.51,  6.4 , 35.01,  7.9 ,
       15.83, 32.18, 18.54, 11.4 , 23.69, 30.76, 36.7 , 10.34, 29.42,
       33.11, 24.3 , 12.94, 17.56, 16.03, 23.83, 38.14,  8.7 , 10.33,
       11.  , 11.6 , 13.86, 23.3 , 29.6 , 17.88, 30.45, 36.19, 30.68])

In [43]:
df.CallingCode.fillna(0).unique().astype('float64')

array([9.300e+01, 3.550e+02, 2.130e+02, 3.760e+02, 2.440e+02, 1.000e+00,
       5.400e+01, 3.740e+02, 6.100e+01, 4.300e+01, 9.940e+02, 9.730e+02,
       8.800e+02, 3.750e+02, 3.200e+01, 5.010e+02, 2.290e+02, 9.750e+02,
       5.910e+02, 3.870e+02, 2.670e+02, 5.500e+01, 6.730e+02, 3.590e+02,
       2.260e+02, 2.570e+02, 2.250e+02, 2.380e+02, 8.550e+02, 2.370e+02,
       2.360e+02, 2.350e+02, 5.600e+01, 8.600e+01, 5.700e+01, 2.690e+02,
       2.420e+02, 5.060e+02, 3.850e+02, 5.300e+01, 3.570e+02, 4.200e+02,
       2.430e+02, 4.500e+01, 2.530e+02, 5.930e+02, 2.000e+01, 5.030e+02,
       2.400e+02, 2.910e+02, 3.720e+02, 2.680e+02, 2.510e+02, 6.790e+02,
       3.580e+02, 3.300e+01, 2.410e+02, 2.200e+02, 9.950e+02, 4.900e+01,
       2.330e+02, 3.000e+01, 5.020e+02, 2.240e+02, 2.450e+02, 5.920e+02,
       5.090e+02, 3.790e+02, 5.040e+02, 3.600e+01, 3.540e+02, 9.100e+01,
       6.200e+01, 9.800e+01, 9.640e+02, 3.530e+02, 9.720e+02, 3.900e+01,
       1.876e+03, 8.100e+01, 9.620e+02, 7.000e+00, 2.540e+02, 6.860e+02,
       9.650e+02, 9.960e+02, 8.560e+02, 3.710e+02, 9.610e+02, 2.660e+02,
       2.310e+02, 2.180e+02, 4.230e+02, 3.700e+02, 3.520e+02, 2.610e+02,
       2.650e+02, 6.000e+01, 9.600e+02, 2.230e+02, 3.560e+02, 6.920e+02,
       2.220e+02, 2.300e+02, 5.200e+01, 6.910e+02, 3.730e+02, 3.770e+02,
       9.760e+02, 3.820e+02, 2.120e+02, 2.580e+02, 9.500e+01, 2.640e+02,
       6.740e+02, 9.770e+02, 3.100e+01, 6.400e+01, 5.050e+02, 2.270e+02,
       2.340e+02, 8.500e+02, 3.890e+02, 4.700e+01, 9.680e+02, 9.200e+01,
       6.800e+02, 0.000e+00, 5.070e+02, 6.750e+02, 5.950e+02, 5.100e+01,
       6.300e+01, 4.800e+01, 3.510e+02, 9.740e+02, 4.000e+01, 2.500e+02,
       6.850e+02, 3.780e+02, 2.390e+02, 9.660e+02, 2.210e+02, 3.810e+02,
       2.480e+02, 2.320e+02, 6.500e+01, 4.210e+02, 3.860e+02, 6.770e+02,
       2.520e+02, 2.700e+01, 8.200e+01, 2.110e+02, 3.400e+01, 9.400e+01,
       2.490e+02, 5.970e+02, 4.600e+01, 4.100e+01, 9.630e+02, 9.920e+02,
       2.550e+02, 6.600e+01, 6.700e+02, 2.280e+02, 6.760e+02, 2.160e+02,
       9.000e+01, 9.930e+02, 6.880e+02, 2.560e+02, 3.800e+02, 9.710e+02,
       4.400e+01, 5.980e+02, 9.980e+02, 6.780e+02, 5.800e+01, 8.400e+01,
       9.670e+02, 2.600e+02, 2.630e+02])

In [45]:
df[df.CapitalMajorCity=='S����']

,Country,Density,Abbreviation,AgriculturalLand,LandArea,ArmedForcessize,BirthRate,CallingCode,CapitalMajorCity,Co2Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,PopulationLaborforceparticipation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
150,S�����������,228,ST,50.7,964,1000,31.54,239.0,S����,121,...,11.70%,0.05,"215,056",57.80%,14.60%,37.00%,13.37%,"158,277",NaN,NaN

In [47]:
df= df.drop(labels=150,axis=0)

In [49]:
df.Largestcity.unique()

array(['Kabul', 'Tirana', 'Algiers', 'Andorra la Vella', 'Luanda',
       "St. John's, Saint John", 'Buenos Aires', 'Yerevan', 'Sydney',
       'Vienna', 'Baku', 'Nassau, Bahamas', 'Riffa', 'Dhaka',
       'Bridgetown', 'Minsk', 'Brussels', 'Belize City', 'Cotonou',
       'Thimphu', 'Santa Cruz de la Sierra', 'Tuzla Canton', 'Gaborone',
       'S����', nan, 'Sofia', 'Ouagadougou', 'Bujumbura', 'Abidjan',
       'Praia', 'Phnom Penh', 'Douala', 'Toronto', 'Bangui', "N'Djamena",
       'Santiago', 'Shanghai', 'Bogot�', 'Moroni, Comoros', 'Brazzaville',
       'San Jos������', 'Zagreb', 'Havana', 'Statos�������', 'Prague',
       'Kinshasa', 'Copenhagen', 'Djibouti City', 'Roseau',
       'Santo Domingo', 'Quito', 'Cairo', 'San Salvador', 'Malabo',
       'Asmara', 'Tallinn', 'Mbabane', 'Addis Ababa', 'Suva', 'Helsinki',
       'Paris', 'Libreville', 'Serekunda', 'Tbilisi', 'Berlin', 'Accra',
       'Macedonia', "St. George's, Grenada", 'Guatemala City', 'Kankan',
       'Bissau', 'Georgetown, Guyana', 'Port-au-Prince', 'Tegucigalpa',
       'Budapest', 'Reykjav��', 'Kurebhar', 'Kalimantan', 'Tehran',
       'Baghdad', 'Connacht', 'Jerusalem', 'Rome', 'Kingston, Jamaica',
       'Tokyo', 'Amman', 'Almaty', 'Nairobi', 'South Tarawa',
       'Kuwait City', 'Bishkek', 'Vientiane', 'Riga', 'Tripoli, Lebanon',
       'Maseru', 'Monrovia', 'Schaan', 'Vilnius', 'Luxembourg City',
       'Antananarivo', 'Lilongwe', 'Johor Bahru', 'Mal�', 'Bamako',
       'Birkirkara', 'Majuro', 'Nouakchott', 'Port Louis', 'Mexico City',
       'Palikir', 'Chi����', 'Monaco City', 'Ulaanbaatar', 'Podgorica',
       'Casablanca', 'Maputo', 'Yangon', 'Windhoek', 'Kathmandu',
       'Amsterdam', 'Auckland', 'Managua', 'Niamey', 'Lagos', 'Pyongyang',
       'Skopje', 'Oslo', 'Seeb', 'Karachi', 'Koror', 'Panama City',
       'Port Moresby', 'Ciudad del Este', 'Lima', 'Manila', 'Warsaw',
       'Lisbon', 'Doha', 'Bucharest', 'Moscow', 'Kigali', 'Basseterre',
       'Castries', 'Calliaqua', 'Apia', 'City of San Marino', 'Riyadh',
       'Pikine', 'Belgrade', 'Victoria, Seychelles', 'Freetown',
       'Bratislava', 'Ljubljana', 'Honiara', 'Bosaso', 'Johannesburg',
       'Seoul', 'Juba', 'Madrid', 'Colombo', 'Omdurman', 'Paramaribo',
       'S�����', 'Z���', 'Damascus', 'Dushanbe', 'Dar es Salaam',
       'Bangkok', 'Dili', 'Lom�', 'Nuku����', 'Chaguanas', 'Tunis',
       'Istanbul', 'Ashgabat', 'Singapore', 'Buganda', 'Kyiv', 'Dubai',
       'London', 'New York City', 'Montevideo', 'Tashkent', 'Port Vila',
       'Caracas', 'Ho Chi Minh City', 'Sanaa', 'Lusaka', 'Harare'],
      dtype=object)

In [51]:
df[df.Largestcity=='S����']

,Country,Density,Abbreviation,AgriculturalLand,LandArea,ArmedForcessize,BirthRate,CallingCode,CapitalMajorCity,Co2Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,PopulationLaborforceparticipation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
23,Brazil,25,BR,33.9,8515770,730000,13.92,55.0,Bras���,"462,299",...,28.30%,2.15,"212,559,417",63.90%,14.20%,65.10%,12.08%,"183,241,641",-14.235004,-51.92528

In [53]:
df= df.drop(labels=23,axis=0)

In [55]:
df[df.Largestcity=='S�����']

,Country,Density,Abbreviation,AgriculturalLand,LandArea,ArmedForcessize,BirthRate,CallingCode,CapitalMajorCity,Co2Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,PopulationLaborforceparticipation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
168,Sweden,25,SE,7.4,450295,30000,11.4,46.0,Stockholm,"43,252",...,15.20%,3.98,"10,285,453",64.60%,27.90%,49.10%,6.48%,"9,021,165",60.128161,18.643501

In [57]:
df= df.drop(labels=168,axis=0)

In [59]:
df[df.Largestcity=='Z���']

,Country,Density,Abbreviation,AgriculturalLand,LandArea,ArmedForcessize,BirthRate,CallingCode,CapitalMajorCity,Co2Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,PopulationLaborforceparticipation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
169,Switzerland,219,CH,38.4,41277,21000,10.0,41.0,Bern,"34,477",...,28.30%,4.3,"8,574,832",68.30%,10.10%,28.80%,4.58%,"6,332,428",46.818188,8.227512

In [61]:
df= df.drop(labels=169,axis=0)

In [63]:
df.Largestcity.replace('�','',regex=True).unique()

array(['Kabul', 'Tirana', 'Algiers', 'Andorra la Vella', 'Luanda',
       "St. John's, Saint John", 'Buenos Aires', 'Yerevan', 'Sydney',
       'Vienna', 'Baku', 'Nassau, Bahamas', 'Riffa', 'Dhaka',
       'Bridgetown', 'Minsk', 'Brussels', 'Belize City', 'Cotonou',
       'Thimphu', 'Santa Cruz de la Sierra', 'Tuzla Canton', 'Gaborone',
       nan, 'Sofia', 'Ouagadougou', 'Bujumbura', 'Abidjan', 'Praia',
       'Phnom Penh', 'Douala', 'Toronto', 'Bangui', "N'Djamena",
       'Santiago', 'Shanghai', 'Bogot', 'Moroni, Comoros', 'Brazzaville',
       'San Jos', 'Zagreb', 'Havana', 'Statos', 'Prague', 'Kinshasa',
       'Copenhagen', 'Djibouti City', 'Roseau', 'Santo Domingo', 'Quito',
       'Cairo', 'San Salvador', 'Malabo', 'Asmara', 'Tallinn', 'Mbabane',
       'Addis Ababa', 'Suva', 'Helsinki', 'Paris', 'Libreville',
       'Serekunda', 'Tbilisi', 'Berlin', 'Accra', 'Macedonia',
       "St. George's, Grenada", 'Guatemala City', 'Kankan', 'Bissau',
       'Georgetown, Guyana', 'Port-au-Prince', 'Tegucigalpa', 'Budapest',
       'Reykjav', 'Kurebhar', 'Kalimantan', 'Tehran', 'Baghdad',
       'Connacht', 'Jerusalem', 'Rome', 'Kingston, Jamaica', 'Tokyo',
       'Amman', 'Almaty', 'Nairobi', 'South Tarawa', 'Kuwait City',
       'Bishkek', 'Vientiane', 'Riga', 'Tripoli, Lebanon', 'Maseru',
       'Monrovia', 'Schaan', 'Vilnius', 'Luxembourg City', 'Antananarivo',
       'Lilongwe', 'Johor Bahru', 'Mal', 'Bamako', 'Birkirkara', 'Majuro',
       'Nouakchott', 'Port Louis', 'Mexico City', 'Palikir', 'Chi',
       'Monaco City', 'Ulaanbaatar', 'Podgorica', 'Casablanca', 'Maputo',
       'Yangon', 'Windhoek', 'Kathmandu', 'Amsterdam', 'Auckland',
       'Managua', 'Niamey', 'Lagos', 'Pyongyang', 'Skopje', 'Oslo',
       'Seeb', 'Karachi', 'Koror', 'Panama City', 'Port Moresby',
       'Ciudad del Este', 'Lima', 'Manila', 'Warsaw', 'Lisbon', 'Doha',
       'Bucharest', 'Moscow', 'Kigali', 'Basseterre', 'Castries',
       'Calliaqua', 'Apia', 'City of San Marino', 'Riyadh', 'Pikine',
       'Belgrade', 'Victoria, Seychelles', 'Freetown', 'Bratislava',
       'Ljubljana', 'Honiara', 'Bosaso', 'Johannesburg', 'Seoul', 'Juba',
       'Madrid', 'Colombo', 'Omdurman', 'Paramaribo', 'Damascus',
       'Dushanbe', 'Dar es Salaam', 'Bangkok', 'Dili', 'Lom', 'Nuku',
       'Chaguanas', 'Tunis', 'Istanbul', 'Ashgabat', 'Singapore',
       'Buganda', 'Kyiv', 'Dubai', 'London', 'New York City',
       'Montevideo', 'Tashkent', 'Port Vila', 'Caracas',
       'Ho Chi Minh City', 'Sanaa', 'Lusaka', 'Harare'], dtype=object)

In [65]:
df.columns

Index(['Country', 'Density', 'Abbreviation', 'AgriculturalLand', 'LandArea',
       'ArmedForcessize', 'BirthRate', 'CallingCode', 'CapitalMajorCity',
       'Co2Emissions', 'CPI', 'CPIChange', 'CurrencyCode', 'FertilityRate',
       'ForestedArea', 'GasolinePrice', 'GDP',
       'Grossprimaryeducationenrollment', 'Grosstertiaryeducationenrollment',
       'Infantmortality', 'Largestcity', 'Lifeexpectancy',
       'Maternalmortalityratio', 'Minimumwage', 'Officiallanguage',
       'Outofpockethealthexpenditure', 'Physiciansperthousand', 'Population',
       'PopulationLaborforceparticipation', 'Taxrevenue', 'Totaltaxrate',
       'Unemploymentrate', 'Urban_population', 'Latitude', 'Longitude'],
      dtype='object')

In [67]:
df=df.drop(['CallingCode','CurrencyCode','Latitude','Longitude'],axis=1)

In [71]:
df.fillna(0)

,Country,Density,Abbreviation,AgriculturalLand,LandArea,ArmedForcessize,BirthRate,CapitalMajorCity,Co2Emissions,CPI,...,Minimumwage,Officiallanguage,Outofpockethealthexpenditure,Physiciansperthousand,Population,PopulationLaborforceparticipation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population
0,Afghanistan,60,AF,58.1,652230,323000,32.49,Kabul,"8,672",149.9,...,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273"
1,Albania,105,AL,43.1,28748,9000,11.78,Tirana,"4,536",119.05,...,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593"
2,Algeria,18,DZ,17.4,2381741,317000,24.28,Algiers,"150,006",151.36,...,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100"
3,Andorra,164,AD,40.0,468,0,7.20,Andorra la Vella,469,0,...,$6.63,Catalan,36.40%,3.33,"77,142",0,0,0,0,"67,873"
4,Angola,26,AO,47.5,1246700,117000,40.73,Luanda,"34,693",261.73,...,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.5,912050,343000,17.88,Caracas,"164,175","2,740.27",...,$0.01,Spanish,45.80%,1.92,"28,515,829",59.70%,0,73.30%,8.80%,"25,162,368"
191,Vietnam,314,VN,39.3,331210,522000,16.75,Hanoi,"192,668",163.52,...,$0.73,Vietnamese,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140"
192,Yemen,56,YE,44.6,527968,40000,30.45,Sanaa,"10,609",157.58,...,0,Arabic,81.00%,0.31,"29,161,922",38.00%,0,26.60%,12.91%,"10,869,523"
193,Zambia,25,ZM,32.1,752618,16000,36.19,Lusaka,"5,141",212.31,...,$0.24,English,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713"
194,Zimbabwe,38,ZW,41.9,390757,51000,30.68,Harare,"10,983",105.51,...,0,Shona,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305"